package ssemi.order.db;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public final class SchemaInitializer {

    private SchemaInitializer() {}

    public static void initialize(Connection conn) {
        try (Statement stmt = conn.createStatement()) {
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS samples (
                    id                  VARCHAR(50)  PRIMARY KEY,
                    name                VARCHAR(100) NOT NULL,
                    avg_production_time INT          NOT NULL,
                    yield               DOUBLE       NOT NULL,
                    stock               INT          NOT NULL DEFAULT 0
                )
                """);
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS orders (
                    order_id       VARCHAR(20)  PRIMARY KEY,
                    sample_id      VARCHAR(50)  NOT NULL REFERENCES samples(id),
                    customer_name  VARCHAR(100) NOT NULL,
                    quantity       INT          NOT NULL,
                    status         VARCHAR(20)  NOT NULL,
                    stock_deducted BOOLEAN      NOT NULL DEFAULT FALSE
                )
                """);
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS production_jobs (
                    job_id        VARCHAR(20) PRIMARY KEY,
                    order_id      VARCHAR(20) NOT NULL REFERENCES orders(order_id),
                    target_qty    INT         NOT NULL,
                    produced_qty  INT         NOT NULL DEFAULT 0,
                    total_time    INT         NOT NULL,
                    start_time    TIMESTAMP,
                    enqueue_order BIGINT GENERATED BY DEFAULT AS IDENTITY
                )
                """);
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS sequences (
                    name     VARCHAR(50) PRIMARY KEY,
                    next_val INT         NOT NULL DEFAULT 1
                )
                """);
            stmt.execute("MERGE INTO sequences (name, next_val) KEY (name) VALUES ('order', 1)");
            stmt.execute("MERGE INTO sequences (name, next_val) KEY (name) VALUES ('job',   1)");
        } catch (SQLException e) {
            throw new IllegalStateException("스키마 초기화 실패: " + e.getMessage(), e);
        }
    }
}
